"""add_phishing_classifier_and_whitelist_tables

Revision ID: 40fd704d8a29
Revises: a7da2453376d
Create Date: 2026-07-24 14:14:34.702335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fd704d8a29'
down_revision: Union[str, Sequence[str], None] = 'a7da2453376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('is_whitelisted', sa.String(length=10), nullable=False),
    sa.Column('triggered_signals', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_risk_assessments_domain'), 'phishing_risk_assessments', ['domain'], unique=True)
    op.create_table('whitelist_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitelist_domains_domain'), 'whitelist_domains', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelist_domains_domain'), table_name='whitelist_domains')
    op.drop_table('whitelist_domains')
    op.drop_index(op.f('ix_phishing_risk_assessments_domain'), table_name='phishing_risk_assessments')
    op.drop_table('phishing_risk_assessments')
    # ### end Alembic commands ###
