"""add company column to active_domain_scans

Revision ID: 5cab4e9edde1
Revises: e85f9214b2d1
Create Date: 2026-08-03 15:06:58.864829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cab4e9edde1'
down_revision: Union[str, Sequence[str], None] = 'e85f9214b2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_domain_scans', sa.Column('company', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_active_domain_scans_company'), 'active_domain_scans', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_domain_scans_company'), table_name='active_domain_scans')
    op.drop_column('active_domain_scans', 'company')
    # ### end Alembic commands ###
