"""Initial active domain scan tables

Revision ID: a7da2453376d
Revises: 
Create Date: 2026-07-24 13:03:25.103674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7da2453376d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_domain_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('dns_resolved', sa.String(length=10), nullable=True),
    sa.Column('ipv4_addresses', sa.Text(), nullable=True),
    sa.Column('ipv6_addresses', sa.Text(), nullable=True),
    sa.Column('http_status', sa.String(length=50), nullable=True),
    sa.Column('redirect_url', sa.Text(), nullable=True),
    sa.Column('ssl_valid', sa.String(length=10), nullable=True),
    sa.Column('ssl_issuer', sa.Text(), nullable=True),
    sa.Column('favicon_sha256', sa.String(length=64), nullable=True),
    sa.Column('spki_sha256', sa.String(length=64), nullable=True),
    sa.Column('dom_body_hash', sa.String(length=64), nullable=True),
    sa.Column('whois_hold', sa.String(length=10), nullable=True),
    sa.Column('urlscan_history', sa.String(length=10), nullable=True),
    sa.Column('urlscan_time', sa.String(length=50), nullable=True),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('correlated_domains', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_domain_scans_domain'), 'active_domain_scans', ['domain'], unique=True)
    op.create_index(op.f('ix_active_domain_scans_favicon_sha256'), 'active_domain_scans', ['favicon_sha256'], unique=False)
    op.create_index(op.f('ix_active_domain_scans_spki_sha256'), 'active_domain_scans', ['spki_sha256'], unique=False)
    op.create_table('active_scan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_scan_history_domain'), 'active_scan_history', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_scan_history_domain'), table_name='active_scan_history')
    op.drop_table('active_scan_history')
    op.drop_index(op.f('ix_active_domain_scans_spki_sha256'), table_name='active_domain_scans')
    op.drop_index(op.f('ix_active_domain_scans_favicon_sha256'), table_name='active_domain_scans')
    op.drop_index(op.f('ix_active_domain_scans_domain'), table_name='active_domain_scans')
    op.drop_table('active_domain_scans')
    # ### end Alembic commands ###
