"""add_page_title_and_form_signals_to_active_domain_scans

Revision ID: c96acda6c566
Revises: 40fd704d8a29
Create Date: 2026-07-24 15:09:14.789278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96acda6c566'
down_revision: Union[str, Sequence[str], None] = '40fd704d8a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_domain_scans', sa.Column('page_title', sa.Text(), nullable=True))
    op.add_column('active_domain_scans', sa.Column('has_password_input', sa.String(length=10), nullable=True))
    op.add_column('active_domain_scans', sa.Column('has_login_form', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_domain_scans', 'has_login_form')
    op.drop_column('active_domain_scans', 'has_password_input')
    op.drop_column('active_domain_scans', 'page_title')
    # ### end Alembic commands ###
